language: node_js

node_js:
    - "iojs"
    - "6"

install:
    - npm run build

notifications:
    email:
        recipients:
            - kevinbird61@gmail.com
        on_success: always
        on_failure: always

script: npm run all
